---
title: "Data analysis for paper : Effect of permethrin contamination during larval development on Anopheles gambiae's life history traits"
author: "Angelique Porciani"
date: today
format:
  html:
    code-fold: true
    html-math-method: katex
    code-tools: true
    self-contained: true
  pdf: default
editor: visual
editor_options: 
  chunk_output_type: console
toc: true
execute:
  warning: false
  message: false
  cache: false
---

```{r}
# package loading 
library(readxl)
library(tidyverse)
library(Rmisc)
library(emmeans)
library(kableExtra)
library(DHARMa)
library(glmmTMB)
library(patchwork)
library(scales)
library(broom.mixed)
library(dplyr)
library(gtsummary)

# data import 
CP_data <- read_excel("../Data/20230503_tous_replicats_choix_pondoir.xlsx") %>% mutate_if(is.character, as.factor) %>% dplyr::rename(concentration_origine=`concentration_permethrine_mg/ml`) 
CP_data <- CP_data %>% 
  mutate(concentration_origine=as.factor(concentration_origine))

BFR_data <- read_excel("../Data/20230503_tous_replicats_taux_gorgement.xlsx")

HatchingR <- read_excel("../Data/20230503_tous_replicats_oeuf_eclosion rate.xlsx") 
HR_2 <- read.csv2("../Data/hatching_02rep.csv")



LHT_data <- read_excel("../Data/20230503_tous_replicats_larves_nymphes_adultes_LHT.xlsx") %>% mutate(jour=as.numeric(as.character(jour))) %>% mutate_if(is.character, as.factor) %>% dplyr::rename(concentration_origine=`concentration_permethrine_mg/ml` , survie=passage_ny1phe ) %>% droplevels() %>% 
  filter(nom!="eau_KIS") 

LHT_data$nom <- factor(LHT_data$nom,
                         levels = c("eau_KDR", "rose_KDR","orange_KDR","rouge_KDR" ),
                         labels = c("0", "2 × 10⁻⁴", "2 × 10⁻³", "2 × 10⁻²"))

```

## Hatching rate

### Data summary

```{r}
# binding of both replicate 
# on ne garde les resultats que pour KDR et pour le jour 1. 
# HR : hatching rate = nb of larvae (alive)
HR_mod <- HatchingR %>% filter(souche=="KDR"& jour=="1") %>% 
  mutate(HR=individus/10) %>% droplevels()

#HR_mod$nom <- factor(HR_mod$nom, levels = c("KDR_eau", "KDR_rose", "KDR_orange", "KDR_rouge"))

HR_2 <- HR_2 %>%  mutate(HR=n_larves_alive/n_eggs)

HR_1_b <- HR_mod %>% select(souche, nom, produit, jour,Conc, individus) %>% mutate(HR=individus/10, replicate=rep(1)) %>% 
  dplyr::rename(n_larves_alive=individus)

HR_2_b <- HR_2 %>% filter(jour==1 & Food==0) %>% select(souche, nom, produit, jour,Conc, n_larves_alive, HR) %>% mutate(replicate=rep(2)) 

# cbind 

HR_mod_tot <- rbind(HR_1_b, HR_2_b)

# Effectif 
HR_mod_tot$nom <- factor(HR_mod_tot$nom, levels = c("KDR_eau", "KDR_rose", "KDR_orange", "KDR_rouge"),
                         labels = c("0", "2 × 10⁻⁴", "2 × 10⁻³", "2 × 10⁻²"))
HR_mod_tot %>% dplyr::group_by(nom, replicate) %>% 
  dplyr::summarise(Effectif=n()) %>% 
  kbl(caption = "Number of wells per replicates", booktabs = T)%>%
	kable_styling(full_width = F)


```

### Model

```{r}

glm_HR_Bin.tot2 <- glm(HR~nom, data=HR_mod_tot, family=quasibinomial(link="logit"))

plot(residuals(glm_HR_Bin.tot2))

#summary(glm_HR_Bin.tot2)

plot(residuals(glm_HR_Bin.tot2))

emm_HR_binFJR <- emmeans(glm_HR_Bin.tot2, revpairwise~nom, infer=TRUE, type="response")

# contrast 
emm_HR_binFJR$contrasts %>% kbl(caption = "Hatching rate comparisons", booktabs = T)%>%
	kable_styling(full_width = F)

# marginal means for plot 
emm_plot_HR <- emm_HR_binFJR$emmeans %>% data.frame() 


```

### Plot

```{r}
HR <- ggplot()+
 # geom_jitter(data=HR_mod_tot,aes(x=nom, y=HR, colour=nom))+
geom_col(data=emm_plot_HR,aes(x=nom, y=prob, colour=nom, fill=nom, alpha = 0.8))+
    geom_errorbar(data=emm_plot_HR,aes(x=nom, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, colour=nom), width=.2,
                 position=position_dodge(.9))+
  theme_classic()+
  ylim(c(0,1))+
      ylab("Hatching Rate")+
  xlab("Permethrin concentration (mg/L)")+
      scale_color_manual(
      values = c("#648FFF","#FF6699", "#FE6100","#CC0000"))+
    scale_fill_manual(
      values = c("#648FFF","#FF6699", "#FE6100","#CC0000"))+
      theme(legend.position = "none", axis.title.x=element_blank())+  
  # scale_x_discrete(labels = c("KDR_eau" = "0", "KDR_rose" = "2.10-4", "KDR_orange" = "2.10-3","KDR_rouge" = "2.10-2" ))
scale_x_discrete(
 labels = c(
      "0",
      expression(2 %*% 10^-4),
      expression(2 %*% 10^-3),
      expression(2 %*% 10^-2)
    )
  )

HR

#ggsave("./img/HR_pic_col.jpeg", width = 20, height = 15, units = "cm")
```

## Mortality rate

### Data summary

```{r}
LHT_data %>% 
  tbl_summary(include = c("nom", "survie"), by = "nom")
```

### Model

```{r}
LHT_mod <- LHT_data %>% dplyr::filter(souche=="kdr"&nom!="NA") %>% 
  dplyr::mutate(concentration_origine2=as.factor(concentration_origine)) %>% 
  #dplyr::filter(sexe!="NA") %>%
  #na.omit(sexe) %>%
  droplevels()

#summary(LHT_mod)

glm_NR_kdr <- glmmTMB(survie~nom+(1|replicat), data=LHT_mod, family=binomial(link="logit"))
#summary(glm_NR_kdr)

# model validation
sim <- simulateResiduals(glm_NR_kdr)
plot(sim)

# results 
emm_NR_kdr <- emmeans(glm_NR_kdr, pairwise~nom, infer=TRUE, type="response")

as.data.frame(emm_NR_kdr$contrasts) %>%
  mutate(
    contrast = as.character(contrast),
    odds.ratio = format(round(odds.ratio, 2), scientific = FALSE),
    SE = format(round(SE, 2), scientific = FALSE),
    df = round(df, 1),
    asymp.LCL= round(asymp.LCL, 3),
    asymp.UCL =round(asymp.UCL,3),
    z.ratio = round(z.ratio, 3),
   p.value = format.pval(p.value, digits = 3, eps = 0.001)
  ) %>%   
  kbl(
    caption = "Comparaisons par paires (emmeans)",
    #col.names = c("Comparaison", "OR", "SE", "df", "Z-ratio", "p-value"),
    align = "c",
    digits=3
  ) %>%
  kable_classic(full_width = FALSE)



```

### Plot

```{r}
plot_emm_PR <- emm_NR_kdr$emmeans %>% data.frame()
plot_emm_PR[4,6] <- 0 # changement des valeurs pour le rouge ou tout est mort
plot_emm_PR[4,5] <- 0 # changement des valeurs pour le rouge ou tout est mort


plot_emm_PR$letter <- c("a","b","c","d")

plot_PR <- plot_emm_PR %>% ggplot()+
   geom_col(aes(x=nom, y=prob, colour=nom, fill=nom, alpha = 0.8))+
    geom_errorbar(aes(x=nom, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, colour=nom), width=.2,
                 position=position_dodge(.9))+
          theme_classic()+
  ylim(c(0,1))+
      ylab("Mortality Rate")+
  xlab("Permethrin concentration (mg/L)")+
        theme(legend.position="none", axis.title.x=element_blank())+  
  scale_color_manual(
      values = c("#648FFF","#FF6699", "#FE6100", "#CC0000"))+
    scale_fill_manual(
      values = c("#648FFF","#FF6699", "#FE6100", "#CC0000"))+
  scale_x_discrete( labels = c(
      "0",
      expression(2 %*% 10^-4),
      expression(2 %*% 10^-3),
      expression(2 %*% 10^-2)
  ))+
  geom_text(data=plot_emm_PR,aes(label = letter, x=nom, y = asymp.UCL), 
            position = position_dodge(width = 1),
    vjust = -0.5, size = 4)

plot_PR

#ggsave("./img/PR_pic.jpeg", width = 30, height = 20, units = "cm")
```

## Time of pupation

```{r}
LHT_mod %>%dplyr::group_by(nom) %>% 
  dplyr::summarise(medianTP=median(jour, na.rm=TRUE)) %>% 
   kbl(caption = "Median time of pupation", booktabs = T)%>%
	kable_styling(full_width = F)
```

Comparaison du jour de pupation à faire 
```{r}

```

## Blood feeding rate

### Data summary

```{r}
BFR_data <- BFR_data %>% mutate_if(is.character, as.factor) 

BFR_data$nom <- factor(BFR_data$nom,
                         levels = c("eau_KDR","rose_KDR","orange_KDR" ),
                         labels = c("0", "2 × 10⁻⁴", "2 × 10⁻³"))

BFR_data %>% 
  tbl_summary(include = c("nom", "gorgee_1"), by = "nom") 

#summary(BFR_data)

BFR_data_mod <- BFR_data %>% filter(souche=="KDR") %>% droplevels()
#summary(BFR_data_mod)

n_gorgee <- BFR_data_mod %>% 
  dplyr::group_by(nom, date_gorgement) %>% 
  dplyr::filter(gorgee=="oui") %>% 
  dplyr::summarise(n_gorgee=n())
  
n_tot <- BFR_data_mod %>% 
  dplyr::group_by(nom, date_gorgement) %>% 
 # dplyr::filter(gorgee=="oui") %>% 
  dplyr::summarise(n_tot=n())

BFR_data_plot <- inner_join(n_gorgee,n_tot) %>% 
  mutate(prop_gorgee=n_gorgee/n_tot)


```

### Model

```{r}
glm_BFR <- glmmTMB(gorgee_1~nom+(1|replicat), data=BFR_data_mod, family=binomial(link="logit"))

emm_BFR <- emmeans(glm_BFR, revpairwise~nom, infer=TRUE, type="response")
#emm_BFR
emm_BFR_plot <- emm_BFR$emmeans %>% data.frame()

# check residuals 

res <- simulateResiduals(glm_BFR)
plot(res)# ok

# contrast 
emm_BFR$contrasts %>% kbl(caption = "Blood feeding rate comparisons", booktabs = T, digits=4)%>%
	kable_styling(full_width = F)
```

### Plot

```{r}
# plot emmean

#emm_BFR_plot$nom <- factor(emm_BFR_plot$nom, levels = c("eau_KDR", "rose_KDR", "orange_KDR"))
emm_BFR_plot$letter <- c("a","b","b")


BFR_plot <-  ggplot()+
 # geom_jitter(data=BFR_data_plot,aes(x=nom, y=prop_gorgee, colour=nom))+
geom_col(data=emm_BFR_plot,aes(x=nom, y=prob, colour=nom, fill=nom, alpha = 0.8))+
    geom_errorbar(data=emm_BFR_plot,aes(x=nom, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, colour=nom), width=.2,
                 position=position_dodge(.9))+
  theme_classic()+
  #ylim(c(0,1))+
      ylab("Blood feeding Rate")+
  xlab("Permethrin concentration (mg/L)")+
      scale_color_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
    scale_fill_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
      theme(legend.position = "none", axis.title.x=element_blank())+  
  scale_x_discrete(
 labels = c(
      "0",
      expression(2 %*% 10^-4),
      expression(2 %*% 10^-3)))+  
  geom_text(data=emm_BFR_plot,aes(label = letter, x=nom, y = asymp.UCL), 
            position = position_dodge(width = 1),
    vjust = -0.5, size = 4)

BFR_plot

#ggsave("./img/BFR_pic_col.jpeg", width = 20, height = 15, units = "cm")

```

## Ovipositing female rate

### Data summary

```{r}
mod_data <- CP_data %>% filter(souche=="kdr")
mod_data$nom <- factor(mod_data$nom,
                         levels = c("eau_KDR","rose_KDR", "orange_KDR"),
                         labels = c("0", "2 × 10⁻⁴", "2 × 10⁻³"))
mod_data %>% 
  tbl_summary(include = c("nom", "ponte_1"), by = "nom",     statistic = all_continuous() ~ "Moy. : {mean}; Median: {median}; SD: {sd}")
```

### Model

```{r}
glm_ponte2 <- glmmTMB(ponte_1~nom+(1|replicat), family= binomial, data= mod_data)

#summary(glm_ponte2)

res <- simulateResiduals(glm_ponte2)
plot(res)#Ok

emm_ovipositionR <- emmeans(glm_ponte2, pairwise~nom, infer=TRUE, type="response")
#emm_ovipositionR


emm_ovipositionR$contrast %>% kbl(caption = "Ovipositing female rate comparisons", booktabs = T, digits=4)%>%
	kable_styling(full_width = F)

```

### Plot

```{r}
# plot 
emm_OR_plot <- emm_ovipositionR$emmeans %>% data.frame()

ELR_plot <- emm_OR_plot%>%  ggplot()+
    #geom_jitter(data=HR_mod_tot,aes(x=nom, y=HR, colour=nom))+
  geom_col(data=emm_OR_plot, aes(x=nom, y=prob, colour=nom, fill=nom, alpha = 0.8))+
    geom_errorbar(data=emm_OR_plot, aes(x=nom, y=prob, ymin=asymp.LCL, ymax=asymp.UCL, colour=nom), width=.2,
                 position=position_dodge(.9))+
          theme_classic()+
  ylim(c(0,1))+
      ylab("Ovipositing female Rate ")+
  xlab("Permethrin concentration (mg/L)")+
        theme(legend.position = "none")+  
  scale_color_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
    scale_fill_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
  scale_x_discrete(
 labels = scales::parse_format()(c(
    "0",
    "2 %*% 10^-4",
    "2 %*% 10^-3"
  )))
ELR_plot

#ggsave("./img/ELR_pic.jpeg", width = 30, height = 20, units = "cm")

```

## Number of eggs

### Model

```{r}
glm4 <- glmmTMB(nbr_oeufs~nom + (1|replicat), data=mod_data, family = nbinom1())

emm_nbrofnR <- emmeans(glm4, pairwise~nom, infer=TRUE, type="response")

res <- simulateResiduals(glm4)
plot(res)#Ok

emm_nbrofnR$contrast %>% kbl(caption = "Number of eggs laid comparisons", booktabs = T, digits=4)%>%
	kable_styling(full_width = F)
```

### Plot

```{r}
emm_nbrofnR_plot <- emm_nbrofnR$emmeans %>% data.frame()

ENb_plot <- emm_nbrofnR_plot %>%  ggplot()+
    #geom_jitter(data=mod_data,aes(x=nom, y=nbr_oeufs, colour=nom))+
  geom_col(data=emm_nbrofnR_plot, aes(x=nom, y=response, colour=nom, fill=nom, alpha = 0.8))+
    geom_errorbar(data=emm_nbrofnR_plot, aes(x=nom, y=response, ymin=asymp.LCL, ymax=asymp.UCL, colour=nom), width=.2,
                 position=position_dodge(.9))+
          theme_classic()+
  #ylim(c(0,1))+
      ylab("Mean egg number per female ")+
  xlab("Permethrin concentration (mg/L)")+
        theme(legend.position = "none")+  
  scale_color_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
    scale_fill_manual(
      values = c("#648FFF","#FF6699", "#FE6100"))+
  scale_x_discrete(
 labels = scales::parse_format()(c(
    "0",
    "2 %*% 10^-4",
    "2 %*% 10^-3",
    "2 %*% 10^-2"
  )))
ENb_plot
#ggsave("./img/Nb_egg_pic.jpeg", width = 30, height = 20, units = "cm")


```

## Figure edition (panel plot)

```{r}
BFR_plot2 <- BFR_plot + theme(plot.margin = margin(10, 20, 10, 20)) + coord_cartesian(clip = "off")
HR_plot    <- HR + coord_cartesian(clip = "off")
plot_PR    <- plot_PR + coord_cartesian(clip = "off")
ELR_plot   <- ELR_plot + coord_cartesian(clip = "off")
ENb_plot   <- ENb_plot + coord_cartesian(clip = "off")

pannel_fig <- HR_plot + plot_PR + BFR_plot2 + ELR_plot + ENb_plot

pannel_fig +
  plot_layout(ncol = 2, byrow = TRUE, heights = c(5,5,5)) +
  plot_annotation(tag_levels = 'A') +
  theme(plot.margin = margin(12, 12, 12, 12))


#ggsave("./img/pannel_4plot.jpeg", width = 30, height = 25, units = "cm")
#ggsave("./img/pannel_4plot.jpeg", width = 10, height = 9, units = "in", dpi = 300)

```
